### ISSUE TITLE
Wegmans 

### ISSUE THREAD

**Issue by sgarfinkel** [ginkgobioworks/vaccinetime#5]
https://www.wegmans.com/covid-vaccine-registration/

This is somewhat complicated and would probably be easiest to scrape with a headless browser or webdriver. That’s how this resource scrapes it: https://github.com/livgust/covid-vaccine-scrapers/tree/master/site-scrapers/Wegmans

Edit: Looks like vaccinespotter may eventually scrape this so might make sense to hold off: https://github.com/GUI/covid-vaccine-spotter/tree/main/src/providers/Wegmans

**Comment by sgarfinkel** [comment]
@dpca I'm working on a scraper based on the first source that uses https://github.com/browserless/chrome and https://github.com/rubycdp/ferrum to drive it. Because Wegman's is especially strange, I'm unsure if you can detect _where_ the appointments are. Might only be able to detect whether appointments are available. Assuming that is OK? In that case posts from the bot would just be gated on appointments becoming available.

**Comment by dpca** [comment]
Cool! One thing to note is that I run vaccinetime in docker on a linux server, so you'll need to get Chrome working in the Dockerfile if you go that route. The other thing is I'd like to try to avoid tweeting about single appointments, since I think that could lead to noise and has the potential to frustrate people because they won't really have a shot at getting them. Could you try digging a little further to see if we could get the number of appointments available, even if we don't know which stores they're in? Like if we can ensure there are at least 10 appointments available somewhere then that would be ideal.

**Comment by sgarfinkel** [comment]
Yeah that docker container works on Linux no problem. And yeah that would definitely be ideal. I'll dig in, but it's challenging because Wegmans will actually need to have appointments before I can see if they show how many they have.

**Comment by dpca** [comment]
Yep I've found that to be a constant challenge of writing these scrapers, you have to actually find the appointments in the first place. What I've sometimes done is write a quick throwaway script that checks a site every minute looking for whatever message they have that says there are no appointments, then notify me when it changes to not say that. So for Wegman's you could write something that looks for the text "All available vaccine appointments are reserved at this time" and then if that isn't there, have it notify you in some way or log as much as you can automatically.
